/**
 * The bench-style end-to-end gate (CS-A step 4): a full
 * Parse → Generate → Render run over a fixture schema through the real
 * pipeline, pinning whole-file C# output byte-for-byte.
 */
import { assertEquals } from 'jsr:@std/assert@^1.0.0'
import { StackTrail, toArtifacts } from '@skmtc/core'
import type { OpenAPIV3 } from 'openapi-types'
import { toCsharpEntry } from '../src/mod.ts'

const csharpEntry = toCsharpEntry({ baseNamespace: 'Acme.Api.Models' })

const documentObject: OpenAPIV3.Document = {
  openapi: '3.0.0',
  info: { title: 'Fixture API', version: '1.0.0' },
  paths: {},
  components: {
    schemas: {
      User: {
        type: 'object',
        description: 'A user of the system',
        properties: {
          user_id: { type: 'string' },
          name: { type: 'string' },
          email: { type: 'string' },
          age: { type: 'integer', format: 'int64' },
          status: { $ref: '#/components/schemas/Status' },
          tags: { type: 'array', items: { type: 'string' } },
          address: {
            type: 'object',
            properties: {
              street: { type: 'string' },
              city: { type: 'string' }
            },
            required: ['street']
          },
          metadata: { type: 'object', additionalProperties: { type: 'string' } },
          list: { $ref: '#/components/schemas/UserList' },
          id: { $ref: '#/components/schemas/UserId' }
        },
        required: ['user_id', 'name']
      },
      Status: {
        type: 'string',
        enum: ['active', 'inactive', 'in-progress']
      },
      UserList: {
        type: 'array',
        items: { $ref: '#/components/schemas/User' }
      },
      UserId: { type: 'string', format: 'uuid' },
      Error: {
        type: 'object',
        properties: { error: { type: 'string' } },
        required: ['error']
      },
      Settings: {
        type: 'object',
        properties: { theme: { type: 'string' } },
        additionalProperties: true
      },
      Task: {
        type: 'object',
        properties: { name: { type: 'string' } },
        required: ['name']
      }
    }
  }
}

const runFixture = () => {
  return toArtifacts({
    traceId: 'gen-csharp-e2e',
    spanId: 'fixture',
    startAt: Date.now(),
    document: { type: 'oas', value: documentObject },
    settings: { basePath: './src' },
    stackTrail: new StackTrail([]),
    silent: true,
    toGeneratorConfigMap: () => ({
      // @ts-expect-error - factory-emitted transform is monomorphic over Acc
      '@skmtc/gen-csharp': csharpEntry
    })
  })
}

Deno.test('e2e - declarable schemas land one type per file; non-declarable refNames produce NO artifact (D6)', () => {
  const { artifacts, manifest } = runFixture()

  // UserList and UserId are non-declarable (array / scalar — C# has no
  // exported type alias) and are skipped-and-inlined; UserAddress is the
  // synthesized inline-object record in its OWN canonical file.
  assertEquals(Object.keys(artifacts).sort(), [
    'src/Acme/Api/Models/Error.generated.cs',
    'src/Acme/Api/Models/Settings.generated.cs',
    'src/Acme/Api/Models/Status.generated.cs',
    'src/Acme/Api/Models/Task.generated.cs',
    'src/Acme/Api/Models/User.generated.cs',
    'src/Acme/Api/Models/UserAddress.generated.cs'
  ])

  assertEquals(manifest.parseIssues.filter(issue => issue.level === 'error'), [])
})

Deno.test('e2e - User renders the CS-A spec worked-example shape (record + inlined non-declarables)', () => {
  const { artifacts } = runFixture()

  assertEquals(
    artifacts['src/Acme/Api/Models/User.generated.cs'],
    '// <auto-generated/>\n' +
      '#nullable enable\n' +
      '\n' +
      'using System;\n' +
      'using System.Collections.Generic;\n' +
      'using System.Text.Json.Serialization;\n' +
      '\n' +
      'namespace Acme.Api.Models;\n' +
      '\n' +
      '/// <summary>\n' +
      '/// A user of the system\n' +
      '/// </summary>\n' +
      'public sealed partial record User\n' +
      '{\n' +
      '    [JsonPropertyName("user_id")]\n' +
      '    public required string UserId { get; init; }\n' +
      '\n' +
      '    [JsonPropertyName("name")]\n' +
      '    public required string Name { get; init; }\n' +
      '\n' +
      '    [JsonPropertyName("email")]\n' +
      '    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]\n' +
      '    public string? Email { get; init; }\n' +
      '\n' +
      '    [JsonPropertyName("age")]\n' +
      '    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]\n' +
      '    public long? Age { get; init; }\n' +
      '\n' +
      '    [JsonPropertyName("status")]\n' +
      '    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]\n' +
      '    public Status? Status { get; init; }\n' +
      '\n' +
      '    [JsonPropertyName("tags")]\n' +
      '    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]\n' +
      '    public IReadOnlyList<string>? Tags { get; init; }\n' +
      '\n' +
      '    [JsonPropertyName("address")]\n' +
      '    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]\n' +
      '    public UserAddress? Address { get; init; }\n' +
      '\n' +
      '    [JsonPropertyName("metadata")]\n' +
      '    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]\n' +
      '    public IReadOnlyDictionary<string, string>? Metadata { get; init; }\n' +
      '\n' +
      '    [JsonPropertyName("list")]\n' +
      '    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]\n' +
      '    public IReadOnlyList<User>? List { get; init; }\n' +
      '\n' +
      '    [JsonPropertyName("id")]\n' +
      '    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]\n' +
      '    public Guid? Id { get; init; }\n' +
      '}\n'
  )
})

Deno.test('e2e - the synthesized inline-object record lands in its own file (same-namespace using suppressed)', () => {
  const { artifacts } = runFixture()

  // User references UserAddress bare — same namespace, so NO using renders
  // in either direction.
  assertEquals(
    artifacts['src/Acme/Api/Models/UserAddress.generated.cs'],
    '// <auto-generated/>\n' +
      '#nullable enable\n' +
      '\n' +
      'using System.Text.Json.Serialization;\n' +
      '\n' +
      'namespace Acme.Api.Models;\n' +
      '\n' +
      'public sealed partial record UserAddress\n' +
      '{\n' +
      '    [JsonPropertyName("street")]\n' +
      '    public required string Street { get; init; }\n' +
      '\n' +
      '    [JsonPropertyName("city")]\n' +
      '    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]\n' +
      '    public string? City { get; init; }\n' +
      '}\n'
  )
})

Deno.test('e2e - Status renders an enum with [JsonStringEnumMemberName] wire values', () => {
  const { artifacts } = runFixture()

  assertEquals(
    artifacts['src/Acme/Api/Models/Status.generated.cs'],
    '// <auto-generated/>\n' +
      '#nullable enable\n' +
      '\n' +
      'using System.Text.Json.Serialization;\n' +
      '\n' +
      'namespace Acme.Api.Models;\n' +
      '\n' +
      '[JsonConverter(typeof(JsonStringEnumConverter))]\n' +
      'public enum Status\n' +
      '{\n' +
      '    [JsonStringEnumMemberName("active")]\n' +
      '    Active,\n' +
      '\n' +
      '    [JsonStringEnumMemberName("inactive")]\n' +
      '    Inactive,\n' +
      '\n' +
      '    [JsonStringEnumMemberName("in-progress")]\n' +
      '    InProgress\n' +
      '}\n'
  )
})

Deno.test('e2e - the CS0542 collision takes the deterministic <Name>Value rename; the attribute keeps the wire name', () => {
  const { artifacts } = runFixture()

  assertEquals(
    artifacts['src/Acme/Api/Models/Error.generated.cs'],
    '// <auto-generated/>\n' +
      '#nullable enable\n' +
      '\n' +
      'using System.Text.Json.Serialization;\n' +
      '\n' +
      'namespace Acme.Api.Models;\n' +
      '\n' +
      'public sealed partial record Error\n' +
      '{\n' +
      '    [JsonPropertyName("error")]\n' +
      '    public required string ErrorValue { get; init; }\n' +
      '}\n'
  )
})

Deno.test('e2e - a mixed object (properties + additionalProperties) carries the [JsonExtensionData] member (D16)', () => {
  const { artifacts } = runFixture()

  assertEquals(
    artifacts['src/Acme/Api/Models/Settings.generated.cs'],
    '// <auto-generated/>\n' +
      '#nullable enable\n' +
      '\n' +
      'using System.Collections.Generic;\n' +
      'using System.Text.Json;\n' +
      'using System.Text.Json.Serialization;\n' +
      '\n' +
      'namespace Acme.Api.Models;\n' +
      '\n' +
      'public sealed partial record Settings\n' +
      '{\n' +
      '    [JsonPropertyName("theme")]\n' +
      '    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]\n' +
      '    public string? Theme { get; init; }\n' +
      '\n' +
      '    [JsonExtensionData]\n' +
      '    public IDictionary<string, JsonElement>? AdditionalProperties { get; init; }\n' +
      '}\n'
  )
})

Deno.test('e2e - a schema shadowing a System type name renders cleanly (A6 fixture)', () => {
  const { artifacts } = runFixture()

  assertEquals(
    artifacts['src/Acme/Api/Models/Task.generated.cs'],
    '// <auto-generated/>\n' +
      '#nullable enable\n' +
      '\n' +
      'using System.Text.Json.Serialization;\n' +
      '\n' +
      'namespace Acme.Api.Models;\n' +
      '\n' +
      'public sealed partial record Task\n' +
      '{\n' +
      '    [JsonPropertyName("name")]\n' +
      '    public required string Name { get; init; }\n' +
      '}\n'
  )
})

Deno.test('e2e - a ref cycle of non-declarables fails the item loudly; the run continues', () => {
  const cycleDocument: OpenAPIV3.Document = {
    openapi: '3.0.0',
    info: { title: 'Cycle API', version: '1.0.0' },
    paths: {},
    components: {
      schemas: {
        LoopA: { $ref: '#/components/schemas/LoopB' },
        LoopB: { $ref: '#/components/schemas/LoopA' },
        Holder: {
          type: 'object',
          properties: { a: { $ref: '#/components/schemas/LoopA' } },
          required: ['a']
        },
        Survivor: {
          type: 'object',
          properties: { ok: { type: 'string' } },
          required: ['ok']
        }
      }
    }
  }

  const { artifacts } = toArtifacts({
    traceId: 'gen-csharp-e2e',
    spanId: 'cycle',
    startAt: Date.now(),
    document: { type: 'oas', value: cycleDocument },
    settings: { basePath: './src' },
    stackTrail: new StackTrail([]),
    silent: true,
    toGeneratorConfigMap: () => ({
      // @ts-expect-error - factory-emitted transform is monomorphic over Acc
      '@skmtc/gen-csharp': csharpEntry
    })
  })

  // Holder errors (loud per-item failure); LoopA/LoopB are non-declarable
  // (no artifact); Survivor still renders — the run continues.
  assertEquals(Object.keys(artifacts), ['src/Acme/Api/Models/Survivor.generated.cs'])
})

// --- Milestone CS-B: abstract-record polymorphic oneOf (D14) ------------

const polymorphicDocumentObject: OpenAPIV3.Document = {
  openapi: '3.0.0',
  info: { title: 'Polymorphic Fixture API', version: '1.0.0' },
  paths: {},
  components: {
    schemas: {
      Animal: {
        oneOf: [
          { $ref: '#/components/schemas/Dog' },
          { $ref: '#/components/schemas/Cat' }
        ],
        discriminator: {
          propertyName: 'petType',
          mapping: {
            dog: '#/components/schemas/Dog',
            cat: '#/components/schemas/Cat'
          }
        }
      },
      Dog: {
        type: 'object',
        properties: {
          petType: { type: 'string' },
          name: { type: 'string' },
          bark_volume: { type: 'integer', format: 'int64' }
        },
        required: ['petType', 'name']
      },
      Cat: {
        type: 'object',
        properties: {
          petType: { type: 'string' },
          name: { type: 'string' }
        },
        required: ['petType', 'name']
      },
      // A member whose ONLY property is the discriminator — legal in C#:
      // renders the bodyless `record Ghost : Spirit;` collapse.
      Spirit: {
        oneOf: [
          { $ref: '#/components/schemas/Ghost' },
          { $ref: '#/components/schemas/Wraith' }
        ],
        discriminator: { propertyName: 'petType' }
      },
      Ghost: {
        type: 'object',
        properties: { petType: { type: 'string' } },
        required: ['petType']
      },
      Wraith: {
        type: 'object',
        properties: {
          petType: { type: 'string' },
          name: { type: 'string' }
        },
        required: ['petType']
      },
      NonQualifying: {
        oneOf: [{ $ref: '#/components/schemas/Dog' }, { type: 'string' }]
      },
      Holder: {
        type: 'object',
        properties: { value: { $ref: '#/components/schemas/NonQualifying' } },
        required: ['value']
      }
    }
  }
}

const runPolymorphicFixture = () => {
  return toArtifacts({
    traceId: 'gen-csharp-e2e',
    spanId: 'polymorphic',
    startAt: Date.now(),
    document: { type: 'oas', value: polymorphicDocumentObject },
    settings: { basePath: './src' },
    stackTrail: new StackTrail([]),
    silent: true,
    toGeneratorConfigMap: () => ({
      // @ts-expect-error - factory-emitted transform is monomorphic over Acc
      '@skmtc/gen-csharp': csharpEntry
    })
  })
}

Deno.test('e2e polymorphic - a qualifying discriminated union renders the parent-side attributes', () => {
  const { artifacts, manifest } = runPolymorphicFixture()

  assertEquals(manifest.parseIssues.filter(issue => issue.level === 'error'), [])

  assertEquals(
    artifacts['src/Acme/Api/Models/Animal.generated.cs'],
    '// <auto-generated/>\n' +
      '#nullable enable\n' +
      '\n' +
      'using System.Text.Json.Serialization;\n' +
      '\n' +
      'namespace Acme.Api.Models;\n' +
      '\n' +
      '[JsonPolymorphic(TypeDiscriminatorPropertyName = "petType")]\n' +
      '[JsonDerivedType(typeof(Dog), "dog")]\n' +
      '[JsonDerivedType(typeof(Cat), "cat")]\n' +
      'public abstract partial record Animal;\n'
  )
})

Deno.test('e2e polymorphic - members carry the base clause and omit the discriminator property', () => {
  const { artifacts } = runPolymorphicFixture()

  assertEquals(
    artifacts['src/Acme/Api/Models/Dog.generated.cs'],
    '// <auto-generated/>\n' +
      '#nullable enable\n' +
      '\n' +
      'using System.Text.Json.Serialization;\n' +
      '\n' +
      'namespace Acme.Api.Models;\n' +
      '\n' +
      'public sealed partial record Dog : Animal\n' +
      '{\n' +
      '    [JsonPropertyName("name")]\n' +
      '    public required string Name { get; init; }\n' +
      '\n' +
      '    [JsonPropertyName("bark_volume")]\n' +
      '    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]\n' +
      '    public long? BarkVolume { get; init; }\n' +
      '}\n'
  )

  assertEquals(
    artifacts['src/Acme/Api/Models/Cat.generated.cs'],
    '// <auto-generated/>\n' +
      '#nullable enable\n' +
      '\n' +
      'using System.Text.Json.Serialization;\n' +
      '\n' +
      'namespace Acme.Api.Models;\n' +
      '\n' +
      'public sealed partial record Cat : Animal\n' +
      '{\n' +
      '    [JsonPropertyName("name")]\n' +
      '    public required string Name { get; init; }\n' +
      '}\n'
  )
})

Deno.test('e2e polymorphic - a multi-parent member fails its item loudly (one base record in C#)', () => {
  const multiParentDocument: OpenAPIV3.Document = {
    openapi: '3.0.0',
    info: { title: 'Multi-Parent API', version: '1.0.0' },
    paths: {},
    components: {
      schemas: {
        First: {
          oneOf: [
            { $ref: '#/components/schemas/Shared' },
            { $ref: '#/components/schemas/Only' }
          ],
          discriminator: { propertyName: 'kind' }
        },
        Second: {
          oneOf: [
            { $ref: '#/components/schemas/Shared' },
            { $ref: '#/components/schemas/Only' }
          ],
          discriminator: { propertyName: 'kind' }
        },
        Shared: {
          type: 'object',
          properties: { kind: { type: 'string' }, value: { type: 'string' } },
          required: ['kind']
        },
        Only: {
          type: 'object',
          properties: { kind: { type: 'string' } },
          required: ['kind']
        },
        Survivor: {
          type: 'object',
          properties: { ok: { type: 'string' } },
          required: ['ok']
        }
      }
    }
  }

  const { artifacts } = toArtifacts({
    traceId: 'gen-csharp-e2e',
    spanId: 'multi-parent',
    startAt: Date.now(),
    document: { type: 'oas', value: multiParentDocument },
    settings: { basePath: './src' },
    stackTrail: new StackTrail([]),
    silent: true,
    toGeneratorConfigMap: () => ({
      // @ts-expect-error - factory-emitted transform is monomorphic over Acc
      '@skmtc/gen-csharp': csharpEntry
    })
  })

  // Shared (claimed by First AND Second) errors loudly — a C# record
  // derives from one base record; Survivor still renders.
  assertEquals(artifacts['src/Acme/Api/Models/Shared.generated.cs'], undefined)
  assertEquals(
    artifacts['src/Acme/Api/Models/Survivor.generated.cs'] !== undefined,
    true
  )
})

Deno.test('e2e polymorphic - a discriminator-only member renders the bodyless collapse with its clause', () => {
  const { artifacts } = runPolymorphicFixture()

  assertEquals(
    artifacts['src/Acme/Api/Models/Ghost.generated.cs'],
    '// <auto-generated/>\n' +
      '#nullable enable\n' +
      '\n' +
      'namespace Acme.Api.Models;\n' +
      '\n' +
      'public sealed partial record Ghost : Spirit;\n'
  )
})

Deno.test('e2e polymorphic - non-qualifying unions stay non-declarable and inline as JsonElement', () => {
  const { artifacts } = runPolymorphicFixture()

  assertEquals(artifacts['src/Acme/Api/Models/NonQualifying.generated.cs'], undefined)

  assertEquals(
    artifacts['src/Acme/Api/Models/Holder.generated.cs'],
    '// <auto-generated/>\n' +
      '#nullable enable\n' +
      '\n' +
      'using System.Text.Json;\n' +
      'using System.Text.Json.Serialization;\n' +
      '\n' +
      'namespace Acme.Api.Models;\n' +
      '\n' +
      'public sealed partial record Holder\n' +
      '{\n' +
      '    [JsonPropertyName("value")]\n' +
      '    public required JsonElement Value { get; init; }\n' +
      '}\n'
  )
})

// --- Milestone CS-D: model renames (CD1) + union hints (CD3) ------------

Deno.test('e2e renames - the alias names identifier, file, ref sites, and polymorphic sites (CD1)', () => {
  const { artifacts } = toArtifacts({
    traceId: 'gen-csharp-e2e',
    spanId: 'renames',
    startAt: Date.now(),
    document: { type: 'oas', value: polymorphicDocumentObject },
    settings: {
      basePath: './src',
      enrichments: {
        '@skmtc/gen-csharp': {
          Dog: { main: { name: 'Hound' } }
        }
      }
    },
    stackTrail: new StackTrail([]),
    silent: true,
    toGeneratorConfigMap: () => ({
      // @ts-expect-error - factory-emitted transform is monomorphic over Acc
      '@skmtc/gen-csharp': csharpEntry
    })
  })

  // The alias names the file…
  assertEquals(artifacts['src/Acme/Api/Models/Dog.generated.cs'], undefined)
  const hound = artifacts['src/Acme/Api/Models/Hound.generated.cs']

  // …the identifier (clause intact)…
  if (!hound.includes('public sealed partial record Hound : Animal')) {
    throw new Error(`Hound shell missing:\n${hound}`)
  }

  // …and the parent's name-only [JsonDerivedType] argument, with the
  // WIRE tag unchanged.
  const animal = artifacts['src/Acme/Api/Models/Animal.generated.cs']
  if (!animal.includes('[JsonDerivedType(typeof(Hound), "dog")]')) {
    throw new Error(`Animal derived-type missing:\n${animal}`)
  }
})

const hintedDocumentObject: OpenAPIV3.Document = {
  openapi: '3.0.0',
  info: { title: 'Hinted Fixture API', version: '1.0.0' },
  paths: {},
  components: {
    schemas: {
      // UNDISCRIMINATED top-level union — upgraded by a hint.
      Pricing: {
        oneOf: [
          { $ref: '#/components/schemas/FixedPrice' },
          { $ref: '#/components/schemas/GraduatedPrice' }
        ]
      },
      FixedPrice: {
        type: 'object',
        properties: {
          pricingType: { type: 'string', enum: ['FIXED'] },
          amount: { type: 'integer', format: 'int64' }
        },
        required: ['pricingType', 'amount']
      },
      GraduatedPrice: {
        type: 'object',
        properties: {
          pricingType: { type: 'string', enum: ['GRADUATED'] },
          tiers: { type: 'array', items: { type: 'integer' } }
        },
        required: ['pricingType']
      },
      // INLINE undiscriminated union one level under properties —
      // upgraded by a named hint; the parent is synthesized. Members
      // are DISTINCT from Pricing's (one base record per C# record).
      ListPrice: {
        type: 'object',
        properties: {
          structure: {
            oneOf: [
              { $ref: '#/components/schemas/TieredPrice' },
              { $ref: '#/components/schemas/VolumePrice' }
            ]
          }
        },
        required: ['structure']
      },
      TieredPrice: {
        type: 'object',
        properties: {
          pricingType: { type: 'string', enum: ['TIERED'] },
          tiers: { type: 'array', items: { type: 'integer' } }
        },
        required: ['pricingType']
      },
      VolumePrice: {
        type: 'object',
        properties: {
          pricingType: { type: 'string', enum: ['VOLUME'] },
          floor: { type: 'integer', format: 'int64' }
        },
        required: ['pricingType']
      },
      // A hint whose members do NOT carry the asserted property —
      // decision 2: the item fails LOUDLY, never a silent fallback.
      Broken: {
        type: 'object',
        properties: {
          value: {
            oneOf: [
              { $ref: '#/components/schemas/FixedPrice' },
              { $ref: '#/components/schemas/Plain' }
            ]
          }
        },
        required: ['value']
      },
      Plain: {
        type: 'object',
        properties: { x: { type: 'string' } },
        required: ['x']
      },
      Survivor: {
        type: 'object',
        properties: { ok: { type: 'string' } },
        required: ['ok']
      }
    }
  }
}

const runHintedFixture = () => {
  return toArtifacts({
    traceId: 'gen-csharp-e2e',
    spanId: 'hinted',
    startAt: Date.now(),
    document: { type: 'oas', value: hintedDocumentObject },
    settings: {
      basePath: './src',
      enrichments: {
        '@skmtc/gen-csharp': {
          Pricing: { main: { discriminator: { propertyName: 'pricingType' } } },
          ListPrice: {
            main: {
              properties: {
                structure: {
                  name: 'PricingStructure',
                  discriminator: { propertyName: 'pricingType' }
                }
              }
            }
          },
          Broken: {
            main: {
              properties: {
                value: {
                  name: 'BrokenUnion',
                  discriminator: { propertyName: 'pricingType' }
                }
              }
            }
          }
        }
      }
    },
    stackTrail: new StackTrail([]),
    silent: true,
    toGeneratorConfigMap: () => ({
      // @ts-expect-error - factory-emitted transform is monomorphic over Acc
      '@skmtc/gen-csharp': csharpEntry
    })
  })
}

Deno.test('e2e hints - a hinted top-level union renders the parent with single-valued-enum tags (CD3)', () => {
  const { artifacts } = runHintedFixture()

  assertEquals(
    artifacts['src/Acme/Api/Models/Pricing.generated.cs'],
    '// <auto-generated/>\n' +
      '#nullable enable\n' +
      '\n' +
      'using System.Text.Json.Serialization;\n' +
      '\n' +
      'namespace Acme.Api.Models;\n' +
      '\n' +
      '[JsonPolymorphic(TypeDiscriminatorPropertyName = "pricingType")]\n' +
      '[JsonDerivedType(typeof(FixedPrice), "FIXED")]\n' +
      '[JsonDerivedType(typeof(GraduatedPrice), "GRADUATED")]\n' +
      'public abstract partial record Pricing;\n'
  )

  // Members carry the clause and omit the asserted property.
  const fixed = artifacts['src/Acme/Api/Models/FixedPrice.generated.cs']
  if (!fixed.includes('public sealed partial record FixedPrice : Pricing')) {
    throw new Error(`FixedPrice clause missing:\n${fixed}`)
  }
  if (fixed.includes('PricingType')) {
    throw new Error(`FixedPrice should omit the discriminator property:\n${fixed}`)
  }
})

Deno.test('e2e hints - an inline hinted union synthesizes the named parent and types the property (CD3)', () => {
  const { artifacts } = runHintedFixture()

  const structure = artifacts['src/Acme/Api/Models/PricingStructure.generated.cs']
  if (!structure.includes('public abstract partial record PricingStructure;')) {
    throw new Error(`synthesized parent missing:\n${structure}`)
  }

  const listPrice = artifacts['src/Acme/Api/Models/ListPrice.generated.cs']
  if (!listPrice.includes('public required PricingStructure Structure { get; init; }')) {
    throw new Error(`ListPrice.structure should be typed PricingStructure:\n${listPrice}`)
  }
})

Deno.test('e2e hints - an invalid hint fails its item loudly; the run continues (CD3 decision 2)', () => {
  const { artifacts } = runHintedFixture()

  // Broken's hinted union members don't carry 'pricingType' (Plain) —
  // the hint is invalid, Broken errors loudly: no artifact. Survivor
  // proves the run continues.
  assertEquals(artifacts['src/Acme/Api/Models/Broken.generated.cs'], undefined)
  assertEquals(artifacts['src/Acme/Api/Models/Survivor.generated.cs'] !== undefined, true)
})
