/**
 * The bench-style end-to-end gate (CS-A step 4): a full
 * Parse → Generate → Render run over a fixture schema through the real
 * pipeline, pinning whole-file C# output byte-for-byte.
 */
import { assertEquals } from 'jsr:@std/assert@^1.0.0'
import { StackTrail, toArtifacts } from '@skmtc/core'
import type { OpenAPIV3 } from 'openapi-types'
import { toCsharpEntry } from '../src/mod.ts'

const csharpEntry = toCsharpEntry({ baseNamespace: 'Acme.Api.Models' })

const documentObject: OpenAPIV3.Document = {
  openapi: '3.0.0',
  info: { title: 'Fixture API', version: '1.0.0' },
  paths: {},
  components: {
    schemas: {
      User: {
        type: 'object',
        description: 'A user of the system',
        properties: {
          user_id: { type: 'string' },
          name: { type: 'string' },
          email: { type: 'string' },
          age: { type: 'integer', format: 'int64' },
          status: { $ref: '#/components/schemas/Status' },
          tags: { type: 'array', items: { type: 'string' } },
          address: {
            type: 'object',
            properties: {
              street: { type: 'string' },
              city: { type: 'string' }
            },
            required: ['street']
          },
          metadata: { type: 'object', additionalProperties: { type: 'string' } },
          list: { $ref: '#/components/schemas/UserList' },
          id: { $ref: '#/components/schemas/UserId' }
        },
        required: ['user_id', 'name']
      },
      Status: {
        type: 'string',
        enum: ['active', 'inactive', 'in-progress']
      },
      UserList: {
        type: 'array',
        items: { $ref: '#/components/schemas/User' }
      },
      UserId: { type: 'string', format: 'uuid' },
      Error: {
        type: 'object',
        properties: { error: { type: 'string' } },
        required: ['error']
      },
      Settings: {
        type: 'object',
        properties: { theme: { type: 'string' } },
        additionalProperties: true
      },
      Task: {
        type: 'object',
        properties: { name: { type: 'string' } },
        required: ['name']
      }
    }
  }
}

const runFixture = () => {
  return toArtifacts({
    traceId: 'gen-csharp-e2e',
    spanId: 'fixture',
    startAt: Date.now(),
    document: { type: 'oas', value: documentObject },
    settings: { basePath: './src' },
    stackTrail: new StackTrail([]),
    silent: true,
    toGeneratorConfigMap: () => ({
      // @ts-expect-error - factory-emitted transform is monomorphic over Acc
      '@skmtc/gen-csharp': csharpEntry
    })
  })
}

Deno.test('e2e - declarable schemas land one type per file; non-declarable refNames produce NO artifact (D6)', () => {
  const { artifacts, manifest } = runFixture()

  // UserList and UserId are non-declarable (array / scalar — C# has no
  // exported type alias) and are skipped-and-inlined; UserAddress is the
  // synthesized inline-object record in its OWN canonical file.
  assertEquals(Object.keys(artifacts).sort(), [
    'src/Acme/Api/Models/Error.generated.cs',
    'src/Acme/Api/Models/Settings.generated.cs',
    'src/Acme/Api/Models/Status.generated.cs',
    'src/Acme/Api/Models/Task.generated.cs',
    'src/Acme/Api/Models/User.generated.cs',
    'src/Acme/Api/Models/UserAddress.generated.cs'
  ])

  assertEquals(manifest.parseIssues.filter(issue => issue.level === 'error'), [])
})

Deno.test('e2e - User renders the CS-A spec worked-example shape (record + inlined non-declarables)', () => {
  const { artifacts } = runFixture()

  assertEquals(
    artifacts['src/Acme/Api/Models/User.generated.cs'],
    '// <auto-generated/>\n' +
      '#nullable enable\n' +
      '\n' +
      'using System;\n' +
      'using System.Collections.Generic;\n' +
      'using System.Text.Json.Serialization;\n' +
      '\n' +
      'namespace Acme.Api.Models;\n' +
      '\n' +
      '/// <summary>\n' +
      '/// A user of the system\n' +
      '/// </summary>\n' +
      'public sealed partial record User\n' +
      '{\n' +
      '    [JsonPropertyName("user_id")]\n' +
      '    public required string UserId { get; init; }\n' +
      '\n' +
      '    [JsonPropertyName("name")]\n' +
      '    public required string Name { get; init; }\n' +
      '\n' +
      '    [JsonPropertyName("email")]\n' +
      '    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]\n' +
      '    public string? Email { get; init; }\n' +
      '\n' +
      '    [JsonPropertyName("age")]\n' +
      '    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]\n' +
      '    public long? Age { get; init; }\n' +
      '\n' +
      '    [JsonPropertyName("status")]\n' +
      '    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]\n' +
      '    public Status? Status { get; init; }\n' +
      '\n' +
      '    [JsonPropertyName("tags")]\n' +
      '    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]\n' +
      '    public IReadOnlyList<string>? Tags { get; init; }\n' +
      '\n' +
      '    [JsonPropertyName("address")]\n' +
      '    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]\n' +
      '    public UserAddress? Address { get; init; }\n' +
      '\n' +
      '    [JsonPropertyName("metadata")]\n' +
      '    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]\n' +
      '    public IReadOnlyDictionary<string, string>? Metadata { get; init; }\n' +
      '\n' +
      '    [JsonPropertyName("list")]\n' +
      '    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]\n' +
      '    public IReadOnlyList<User>? List { get; init; }\n' +
      '\n' +
      '    [JsonPropertyName("id")]\n' +
      '    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]\n' +
      '    public Guid? Id { get; init; }\n' +
      '}\n'
  )
})

Deno.test('e2e - the synthesized inline-object record lands in its own file (same-namespace using suppressed)', () => {
  const { artifacts } = runFixture()

  // User references UserAddress bare — same namespace, so NO using renders
  // in either direction.
  assertEquals(
    artifacts['src/Acme/Api/Models/UserAddress.generated.cs'],
    '// <auto-generated/>\n' +
      '#nullable enable\n' +
      '\n' +
      'using System.Text.Json.Serialization;\n' +
      '\n' +
      'namespace Acme.Api.Models;\n' +
      '\n' +
      'public sealed partial record UserAddress\n' +
      '{\n' +
      '    [JsonPropertyName("street")]\n' +
      '    public required string Street { get; init; }\n' +
      '\n' +
      '    [JsonPropertyName("city")]\n' +
      '    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]\n' +
      '    public string? City { get; init; }\n' +
      '}\n'
  )
})

Deno.test('e2e - Status renders an enum with [JsonStringEnumMemberName] wire values', () => {
  const { artifacts } = runFixture()

  assertEquals(
    artifacts['src/Acme/Api/Models/Status.generated.cs'],
    '// <auto-generated/>\n' +
      '#nullable enable\n' +
      '\n' +
      'using System.Text.Json.Serialization;\n' +
      '\n' +
      'namespace Acme.Api.Models;\n' +
      '\n' +
      '[JsonConverter(typeof(JsonStringEnumConverter))]\n' +
      'public enum Status\n' +
      '{\n' +
      '    [JsonStringEnumMemberName("active")]\n' +
      '    Active,\n' +
      '\n' +
      '    [JsonStringEnumMemberName("inactive")]\n' +
      '    Inactive,\n' +
      '\n' +
      '    [JsonStringEnumMemberName("in-progress")]\n' +
      '    InProgress\n' +
      '}\n'
  )
})

Deno.test('e2e - the CS0542 collision takes the deterministic <Name>Value rename; the attribute keeps the wire name', () => {
  const { artifacts } = runFixture()

  assertEquals(
    artifacts['src/Acme/Api/Models/Error.generated.cs'],
    '// <auto-generated/>\n' +
      '#nullable enable\n' +
      '\n' +
      'using System.Text.Json.Serialization;\n' +
      '\n' +
      'namespace Acme.Api.Models;\n' +
      '\n' +
      'public sealed partial record Error\n' +
      '{\n' +
      '    [JsonPropertyName("error")]\n' +
      '    public required string ErrorValue { get; init; }\n' +
      '}\n'
  )
})

Deno.test('e2e - a mixed object (properties + additionalProperties) carries the [JsonExtensionData] member (D16)', () => {
  const { artifacts } = runFixture()

  assertEquals(
    artifacts['src/Acme/Api/Models/Settings.generated.cs'],
    '// <auto-generated/>\n' +
      '#nullable enable\n' +
      '\n' +
      'using System.Collections.Generic;\n' +
      'using System.Text.Json;\n' +
      'using System.Text.Json.Serialization;\n' +
      '\n' +
      'namespace Acme.Api.Models;\n' +
      '\n' +
      'public sealed partial record Settings\n' +
      '{\n' +
      '    [JsonPropertyName("theme")]\n' +
      '    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]\n' +
      '    public string? Theme { get; init; }\n' +
      '\n' +
      '    [JsonExtensionData]\n' +
      '    public IDictionary<string, JsonElement>? AdditionalProperties { get; init; }\n' +
      '}\n'
  )
})

Deno.test('e2e - a schema shadowing a System type name renders cleanly (A6 fixture)', () => {
  const { artifacts } = runFixture()

  assertEquals(
    artifacts['src/Acme/Api/Models/Task.generated.cs'],
    '// <auto-generated/>\n' +
      '#nullable enable\n' +
      '\n' +
      'using System.Text.Json.Serialization;\n' +
      '\n' +
      'namespace Acme.Api.Models;\n' +
      '\n' +
      'public sealed partial record Task\n' +
      '{\n' +
      '    [JsonPropertyName("name")]\n' +
      '    public required string Name { get; init; }\n' +
      '}\n'
  )
})

Deno.test('e2e - a ref cycle of non-declarables fails the item loudly; the run continues', () => {
  const cycleDocument: OpenAPIV3.Document = {
    openapi: '3.0.0',
    info: { title: 'Cycle API', version: '1.0.0' },
    paths: {},
    components: {
      schemas: {
        LoopA: { $ref: '#/components/schemas/LoopB' },
        LoopB: { $ref: '#/components/schemas/LoopA' },
        Holder: {
          type: 'object',
          properties: { a: { $ref: '#/components/schemas/LoopA' } },
          required: ['a']
        },
        Survivor: {
          type: 'object',
          properties: { ok: { type: 'string' } },
          required: ['ok']
        }
      }
    }
  }

  const { artifacts } = toArtifacts({
    traceId: 'gen-csharp-e2e',
    spanId: 'cycle',
    startAt: Date.now(),
    document: { type: 'oas', value: cycleDocument },
    settings: { basePath: './src' },
    stackTrail: new StackTrail([]),
    silent: true,
    toGeneratorConfigMap: () => ({
      // @ts-expect-error - factory-emitted transform is monomorphic over Acc
      '@skmtc/gen-csharp': csharpEntry
    })
  })

  // Holder errors (loud per-item failure); LoopA/LoopB are non-declarable
  // (no artifact); Survivor still renders — the run continues.
  assertEquals(Object.keys(artifacts), ['src/Acme/Api/Models/Survivor.generated.cs'])
})
