/**
 * The bench-style end-to-end gate (CS-C): a full Parse → Generate →
 * Render run through the real pipeline, pinning whole-file C# output
 * byte-for-byte — composed with gen-csharp so DTO references resolve.
 */
import { assertEquals, assertStringIncludes } from 'jsr:@std/assert@^1.0.0'
import { StackTrail, toArtifacts } from '@skmtc/core'
import type { OpenAPIV3 } from 'openapi-types'
import { toCsharpEntry } from '@skmtc/gen-csharp'
import { toCsharpAspnetEntry } from '../src/mod.ts'

const csharpEntry = toCsharpEntry({ baseNamespace: 'Acme.Api.Models' })
const aspnetEntry = toCsharpAspnetEntry({ baseNamespace: 'Acme.Api' })

const documentObject: OpenAPIV3.Document = {
  openapi: '3.0.0',
  info: { title: 'Fixture API', version: '1.0.0' },
  paths: {
    '/users': {
      get: {
        tags: ['Users'],
        summary: 'List all users',
        parameters: [
          {
            name: 'limit',
            in: 'query',
            required: false,
            schema: { type: 'integer' }
          },
          {
            name: 'X-Tenant',
            in: 'header',
            required: true,
            schema: { type: 'string' }
          }
        ],
        responses: {
          '200': {
            description: 'Users',
            content: {
              'application/json': {
                schema: { type: 'array', items: { $ref: '#/components/schemas/User' } }
              }
            }
          }
        }
      },
      post: {
        tags: ['Users'],
        requestBody: {
          required: true,
          content: {
            'application/json': { schema: { $ref: '#/components/schemas/UserCreate' } }
          }
        },
        responses: {
          '201': {
            description: 'Created',
            content: {
              'application/json': { schema: { $ref: '#/components/schemas/User' } }
            }
          }
        }
      }
    },
    '/users/{id}': {
      delete: {
        tags: ['Users'],
        parameters: [
          { name: 'id', in: 'path', required: true, schema: { type: 'string' } }
        ],
        responses: { '204': { description: 'Deleted' } }
      }
    },
    '/ping': {
      get: {
        responses: {
          '200': {
            description: 'Pong',
            content: { 'application/json': { schema: { type: 'string' } } }
          }
        }
      }
    }
  },
  components: {
    schemas: {
      User: {
        type: 'object',
        properties: { user_id: { type: 'string' }, name: { type: 'string' } },
        required: ['user_id', 'name']
      },
      UserCreate: {
        type: 'object',
        properties: { name: { type: 'string' } },
        required: ['name']
      }
    }
  }
}

const runFixture = () => {
  return toArtifacts({
    traceId: 'gen-csharp-aspnet-e2e',
    spanId: 'fixture',
    startAt: Date.now(),
    document: { type: 'oas', value: documentObject },
    settings: { basePath: './src' },
    stackTrail: new StackTrail([]),
    silent: true,
    toGeneratorConfigMap: () => ({
      // @ts-expect-error - factory-emitted transform is monomorphic over Acc
      '@skmtc/gen-csharp': csharpEntry,
      // @ts-expect-error - factory-emitted transform is monomorphic over Acc
      '@skmtc/gen-csharp-aspnet': aspnetEntry
    })
  })
}

Deno.test('e2e aspnet - one file per tag, untagged lands in DefaultApi, the 204 helper is emitted once', () => {
  const { artifacts, manifest } = runFixture()

  assertEquals(Object.keys(artifacts).sort(), [
    'src/Acme/Api/ApiException.generated.cs',
    'src/Acme/Api/ApiExceptionHandler.generated.cs',
    'src/Acme/Api/DefaultApi.generated.cs',
    'src/Acme/Api/GeneratedResults.generated.cs',
    'src/Acme/Api/Models/User.generated.cs',
    'src/Acme/Api/Models/UserCreate.generated.cs',
    'src/Acme/Api/UsersApi.generated.cs'
  ])

  assertEquals(manifest.parseIssues.filter(issue => issue.level === 'error'), [])
})

Deno.test('e2e aspnet - the UsersApi file renders the seam interface + delegating controller byte-for-byte', () => {
  const { artifacts } = runFixture()

  assertEquals(
    artifacts['src/Acme/Api/UsersApi.generated.cs'],
    '// <auto-generated/>\n' +
      '#nullable enable\n' +
      '\n' +
      'using Acme.Api.Models;\n' +
      'using Microsoft.AspNetCore.Mvc;\n' +
      'using System.Collections.Generic;\n' +
      'using System.Threading.Tasks;\n' +
      '\n' +
      'namespace Acme.Api;\n' +
      '\n' +
      'public interface IUsersService\n' +
      '{\n' +
      '    /// <summary>\n' +
      '    /// List all users\n' +
      '    /// </summary>\n' +
      '    Task<IReadOnlyList<User>> GetUsers(string xTenant, int? limit = null);\n' +
      '\n' +
      '    Task<User> PostUsers(UserCreate body);\n' +
      '\n' +
      '    Task DeleteUsersId(string id);\n' +
      '}\n' +
      '\n' +
      '[ApiController]\n' +
      'public sealed partial class UsersController(IUsersService service) : ControllerBase\n' +
      '{\n' +
      '    [HttpGet("/users")]\n' +
      '    public async Task<IReadOnlyList<User>> GetUsers([FromHeader(Name = "X-Tenant")] string xTenant, [FromQuery(Name = "limit")] int? limit) => await service.GetUsers(xTenant, limit);\n' +
      '\n' +
      '    [HttpPost("/users")]\n' +
      '    [ProducesResponseType(201)]\n' +
      '    public async Task<ActionResult<User>> PostUsers([FromBody] UserCreate body) => StatusCode(201, await service.PostUsers(body));\n' +
      '\n' +
      '    [HttpDelete("/users/{id}")]\n' +
      '    [ProducesResponseType(204)]\n' +
      '    public async Task<IActionResult> DeleteUsersId([FromRoute(Name = "id")] string id) => await GeneratedResults.NoContent(service.DeleteUsersId(id));\n' +
      '}\n'
  )
})

Deno.test('e2e aspnet - the GeneratedResults helper renders complete (no stubs)', () => {
  const { artifacts } = runFixture()

  assertEquals(
    artifacts['src/Acme/Api/GeneratedResults.generated.cs'],
    '// <auto-generated/>\n' +
      '#nullable enable\n' +
      '\n' +
      'using Microsoft.AspNetCore.Mvc;\n' +
      'using System.Threading.Tasks;\n' +
      '\n' +
      'namespace Acme.Api;\n' +
      '\n' +
      '/// <summary>\n' +
      '/// Sequencing helpers the generated expression-bodied actions delegate to.\n' +
      '/// </summary>\n' +
      'public sealed partial class GeneratedResults\n' +
      '{\n' +
      '    public static async Task<IActionResult> NoContent(Task task)\n' +
      '    {\n' +
      '        await task;\n' +
      '        return new NoContentResult();\n' +
      '    }\n' +
      '}\n'
  )
})

Deno.test('e2e aspnet - the untagged operation lands in DefaultApi with the 200-style shape', () => {
  const { artifacts } = runFixture()

  const defaultApi = artifacts['src/Acme/Api/DefaultApi.generated.cs']

  assertStringIncludes(defaultApi, 'public interface IDefaultService')
  assertStringIncludes(defaultApi, 'Task<string> GetPing();')
  assertStringIncludes(
    defaultApi,
    'public sealed partial class DefaultController(IDefaultService service) : ControllerBase'
  )
  assertStringIncludes(
    defaultApi,
    '    [HttpGet("/ping")]\n' +
      '    public async Task<string> GetPing() => await service.GetPing();'
  )
})

Deno.test('e2e aspnet - the error channel renders the ApiException + handler pair (CD4)', () => {
  const { artifacts } = runFixture()

  assertEquals(
    artifacts['src/Acme/Api/ApiException.generated.cs'],
    '// <auto-generated/>\n' +
      '#nullable enable\n' +
      '\n' +
      'using System;\n' +
      '\n' +
      'namespace Acme.Api;\n' +
      '\n' +
      '/// <summary>\n' +
      '/// A status-bearing error thrown by service implementations; ApiExceptionHandler renders it as a ProblemDetails response.\n' +
      '/// </summary>\n' +
      'public sealed partial class ApiException(int statusCode, string message) : Exception(message)\n' +
      '{\n' +
      '    public int StatusCode { get; } = statusCode;\n' +
      '}\n'
  )

  const handler = artifacts['src/Acme/Api/ApiExceptionHandler.generated.cs']
  assertStringIncludes(
    handler,
    'public sealed partial class ApiExceptionHandler : IExceptionHandler'
  )
  assertStringIncludes(handler, 'if (exception is not ApiException apiException)')
  assertStringIncludes(handler, 'new ProblemDetails')
})

Deno.test('e2e aspnet - serviceMethodName renames seam and controller in lockstep (CD2)', () => {
  const { artifacts } = toArtifacts({
    traceId: 'gen-csharp-aspnet-e2e',
    spanId: 'rename',
    startAt: Date.now(),
    document: { type: 'oas', value: documentObject },
    settings: {
      basePath: './src',
      enrichments: {
        '@skmtc/gen-csharp-aspnet': {
          '/users': { post: { main: { serviceMethodName: 'CreateUser' } } }
        }
      }
    },
    stackTrail: new StackTrail([]),
    silent: true,
    toGeneratorConfigMap: () => ({
      // @ts-expect-error - factory-emitted transform is monomorphic over Acc
      '@skmtc/gen-csharp': csharpEntry,
      // @ts-expect-error - factory-emitted transform is monomorphic over Acc
      '@skmtc/gen-csharp-aspnet': aspnetEntry
    })
  })

  const usersApi = artifacts['src/Acme/Api/UsersApi.generated.cs']

  assertStringIncludes(usersApi, 'Task<User> CreateUser(UserCreate body);')
  assertStringIncludes(
    usersApi,
    'public async Task<ActionResult<User>> CreateUser([FromBody] UserCreate body) => StatusCode(201, await service.CreateUser(body));'
  )
})
